version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: ecommerce-postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - ecommerce-pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - ecommerce-net

  activemq-artemis:
    image: vromero/activemq-artemis
    container_name: ecommerce-activemq-artemis
    environment:
      ARTEMIS_USERNAME: ${ARTEMIS_USERNAME}
      ARTEMIS_PASSWORD: ${ARTEMIS_PASSWORD}
      ARTEMIS_ROLE: ${ARTEMIS_ROLE}
    ports:
      - "61616:61616"   # JMS
      - "8161:8161"     # management console
      - "5672:5672"     # AMQP (optional)
      - "1883:1883"     # MQTT (optional)
      - "61613:61613"   # STOMP (optional)
    volumes:
      - activemq-artemis-data:/var/lib/artemis/data
    networks:
      - ecommerce-net

  zookeeper:
    image: docker.io/library/zookeeper:3.8
    container_name: ecommerce-zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - "2181:2181"
    networks:
      - ecommerce-net

#  kafka:
#    image: confluentinc/cp-kafka:latest
#    depends_on:
#      - zookeeper
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
##      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
##      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_BROKER_ID: 1
#      KAFKA_LISTENERS: PLAINTEXT://:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_PROCESS_ROLES: broker
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
#      KAFKA_NUM_PARTITIONS: 3
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka:
    image: bitnamilegacy/kafka:3.6.1-debian-11-r0
    container_name: ecommerce-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      # KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      # KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
    ports:
      - "9092:9092"
    networks:
      - ecommerce-net
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
    - ecommerce-redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - ecommerce-net

  order-service:
    build: ./order-service
    container_name: ecommerce-order-service
    depends_on:
      postgres:
        condition: service_started
      activemq-artemis:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      SERVER_PORT: 8090
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce_order
      SPRING_DATASOURCE_USERNAME: ecommerce_order
      SPRING_DATASOURCE_PASSWORD: ecommerce_order
      BASE_CURRENCY: ${BASE_CURRENCY}
      ACTIVEMQ_USERNAME: ${ACTIVEMQ_USERNAME}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      ACTIVEMQ_BROKER_URL: ${ACTIVEMQ_BROKER_URL}
      ACTIVEMQ_HOST: activemq-artemis
      ACTIVEMQ_PORT: 61616
    ports:
      - "8090:8090"
    networks:
      - ecommerce-net

  integration-service:
    build: ./integration-service
    container_name: integration-service
    depends_on:
      - postgres
      - activemq-artemis
      - kafka
    environment:
      SERVER_PORT: 8050
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce_integration
      SPRING_DATASOURCE_USERNAME: ecommerce_integration
      SPRING_DATASOURCE_PASSWORD: ecommerce_integration
      ACTIVEMQ_USERNAME: ${ACTIVEMQ_USERNAME}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      ACTIVEMQ_BROKER_URL: ${ACTIVEMQ_BROKER_URL}
      ACTIVEMQ_HOST: activemq-artemis
      ACTIVEMQ_PORT: 61616
      MAIL_GMAIL_USERNAME: ${MAIL_GMAIL_USERNAME}
      MAIL_GMAIL_PASSWORD: ${MAIL_GMAIL_PASSWORD}
      MAIL_GMAIL_IMAP_HOST: ${MAIL_GMAIL_IMAP_HOST}
      MAIL_GMAIL_IMAP_PORT: ${MAIL_GMAIL_IMAP_PORT}
      MAIL_GMAIL_SMTP_HOST: ${MAIL_GMAIL_SMTP_HOST}
      MAIL_GMAIL_SMTP_PORT: ${MAIL_GMAIL_SMTP_PORT}
      MAIL_GMAIL_IMAP_FOLDER_NAME: ${MAIL_GMAIL_IMAP_FOLDER_NAME}
    ports:
      - "8050:8050"
    networks:
      - ecommerce-net

  notification-service:
    build: ./notification-service
    container_name: ecommerce-notification-service
    environment:
      KAFKA_BROKERS: kafka:9092
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: ${SMTP_FROM}
      TWILIO_SID: ${TWILIO_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_FROM: ${TWILIO_FROM}
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "3050:3050"
    networks:
      - ecommerce-net

volumes:
  ecommerce-pgdata:
  activemq-artemis-data:
  ecommerce-redis-data:

networks:
  ecommerce-net:
    driver: bridge

