spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:}
    user: ${ACTIVEMQ_USERNAME:}
    password: ${ACTIVEMQ_PASSWORD:}
  artemis:
    mode: native
    broker-url: ${ACTIVEMQ_BROKER_URL:}
    user: ${ACTIVEMQ_USERNAME:}
    password: ${ACTIVEMQ_PASSWORD:}
    host: ${ACTIVEMQ_HOST:activemq-artemis}
    port: ${ACTIVEMQ_PORT:61616}
  kafka:
    brokers: kafka:9092
    bootstrap-servers: kafka:9092
#    key-serializer: org.apache.kafka.common.serialization.StringSerializer
#    value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      acks: all
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  configs:
    currency:
      base: ${BASE_CURRENCY:}
